import { attachGalleryPhoto, expect, saveRecord, test, waitForRecordHome } from '../helpers'

test.describe('E2E-07 魚種図鑑', () => {
  test('E2E-07a 魚種なし記録だけ', async ({ freshPage: page }) => {
    await waitForRecordHome(page)
    await saveRecord(page)
    await page.goto('/mypage/encyclopedia')
    await expect(page.getByRole('heading', { name: 'マイ魚種図鑑' })).toBeVisible()
    const totals = page.getByTestId('encyclopedia-totals')
    await expect(totals).toContainText('0種')
    await expect(totals).toContainText('0匹')
    await expect(page.getByText('魚種付きの記録がまだありません')).toBeVisible()
    await expect(page.getByTestId('encyclopedia-search')).toHaveCount(0)
  })

  test('E2E-07b アジを保存 → 図鑑カードから詳細', async ({ freshPage: page }) => {
    await waitForRecordHome(page)
    await page.getByLabel('魚種（任意）').fill('アジ')
    await page.keyboard.press('Escape')
    await saveRecord(page)
    await page.goto('/mypage/encyclopedia')
    const totals = page.getByTestId('encyclopedia-totals')
    await expect(totals).toContainText('1種')
    await expect(totals).toContainText('1匹')
    const card = page.getByRole('link', { name: /アジ/ })
    await expect(card).toBeVisible()
    await expect(card.getByRole('img')).toHaveCount(0)
    await card.click()
    await expect(page.getByRole('heading', { name: 'アジ' })).toBeVisible()
    await expect(page.getByText('アジ').nth(0)).toBeVisible()
  })

  test('E2E-07c 写真付きアジ → 図鑑カードに代表画像', async ({ freshPage: page }) => {
    await waitForRecordHome(page)
    await attachGalleryPhoto(page)
    await page.getByLabel('魚種（任意）').fill('アジ')
    await page.keyboard.press('Escape')
    await saveRecord(page)
    await page.goto('/mypage/encyclopedia')
    const card = page.getByRole('link', { name: /アジ/ })
    await expect(card).toBeVisible()
    await expect(card.getByRole('img', { name: 'アジの代表画像' })).toBeVisible()
  })

  test('E2E-07d アジとヒラメ → 検索で絞り込み', async ({ freshPage: page }) => {
    await waitForRecordHome(page)
    await page.getByLabel('魚種（任意）').fill('アジ')
    await page.keyboard.press('Escape')
    await saveRecord(page)
    await page.getByTestId('record-continue').click()
    await page.getByLabel('魚種（任意）').fill('ヒラメ')
    await page.keyboard.press('Escape')
    await saveRecord(page)

    await page.goto('/mypage/encyclopedia')
    const totals = page.getByTestId('encyclopedia-totals')
    await expect(totals).toContainText('2種')
    await expect(page.getByRole('link', { name: /アジ/ })).toBeVisible()
    await expect(page.getByRole('link', { name: /ヒラメ/ })).toBeVisible()

    const search = page.getByTestId('encyclopedia-search')
    await search.fill('アジ')
    await expect(page.getByRole('link', { name: /アジ/ })).toBeVisible()
    await expect(page.getByRole('link', { name: /ヒラメ/ })).toHaveCount(0)
    await expect(totals).toContainText('2種')

    await search.fill('いない魚')
    await expect(page.getByText('該当する魚種がありません')).toBeVisible()
    await expect(totals).toContainText('2種')

    await page.getByTestId('encyclopedia-search-clear').click()
    await expect(search).toHaveValue('')
    await expect(page.getByRole('link', { name: /アジ/ })).toBeVisible()
    await expect(page.getByRole('link', { name: /ヒラメ/ })).toBeVisible()
  })

  test('E2E-07e アジを匹数 3 で保存 → 図鑑は 3匹', async ({ freshPage: page }) => {
    await waitForRecordHome(page)
    await page.getByLabel('魚種（任意）').fill('アジ')
    await page.keyboard.press('Escape')
    await page.getByLabel('匹数').fill('3')
    await saveRecord(page)
    await page.goto('/mypage/encyclopedia')
    const totals = page.getByTestId('encyclopedia-totals')
    await expect(totals).toContainText('1種')
    await expect(totals).toContainText('3匹')
    const card = page.getByRole('link', { name: /アジ/ })
    await expect(card).toContainText('3匹')
  })

  test('E2E-07f ルアー条件で詳細の一覧を絞る', async ({ freshPage: page }) => {
    await waitForRecordHome(page)
    await page.getByLabel('魚種（任意）').fill('アジ')
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: 'タックル入力を開く' }).click()
    await page.getByRole('combobox', { name: 'ルアー' }).fill('ミノー')
    await page.keyboard.press('Escape')
    await saveRecord(page)
    await page.goto('/mypage/encyclopedia')
    await page.getByRole('link', { name: /アジ/ }).click()
    await expect(page.getByRole('heading', { name: 'アジ' })).toBeVisible()
    const pattern = page.getByTestId('catch-pattern')
    await expect(pattern).toBeVisible()
    const lureBar = pattern.getByRole('button', { name: /ミノー/ })
    await expect(lureBar).toHaveCount(0)
    await page.getByRole('button', { name: 'よく釣れている条件を開く' }).click()
    await expect(pattern).toContainText('ルアー／エサ')
    await expect(lureBar).toBeVisible()
    await lureBar.click()
    await expect(page.getByText('ミノーで絞り込み中')).toBeVisible()
    await expect(page.getByRole('heading', { name: '記録一覧（ミノー）' })).toBeVisible()
    await page.getByRole('button', { name: '解除' }).click()
    await expect(page.getByText('ミノーで絞り込み中')).toHaveCount(0)
    await expect(page.getByRole('heading', { name: '記録一覧', exact: true })).toBeVisible()
  })
})
